sudo: required

language: generic

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=cassinyio/deeplearning-gpu
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker push $REPO
